### ISSUE TITLE
【严重问题】脚本无法加载，没有下载按钮

### ISSUE THREAD

**Issue by Aarondongsq** [amakerlife/tchMaterial-downloader#5]
![image](https://github.com/user-attachments/assets/9ed2e891-0e24-4811-a2a2-e3a5f136a114)
无法显示下载按钮，脚本没有加载

**Comment by amakerlife** [comment]
> ![image](https://private-user-images.githubusercontent.com/103747820/383456387-9ed2e891-0e24-4811-a2a2-e3a5f136a114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTY1MzksIm5iZiI6MTczMDg5NjIzOSwicGF0aCI6Ii8xMDM3NDc4MjAvMzgzNDU2Mzg3LTllZDJlODkxLTBlMjQtNDgxMS1hMmEyLWUzYTVmMTM2YTExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQxMjMwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjVjMzBjZDJmZDhiZDU5MDY0ODVmZDAzYTM0YjkwNTdjOTRkNDEwMzFmYTRlNDBiZDE3NTkyNDU5NzczYWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jFeXcYaOw99D1p_OeWfg4TX-at30xX5oepq2t3Pw4Qs) 无法显示下载按钮，脚本没有加载

请选择需要下载的教材并点击。
